### ISSUE TITLE
Can this work on a shared hosting?

### ISSUE THREAD

**Issue by sysads** [patrikzudel/PatrikZeros-ChatGPT-API-UI#32]

**Comment by Brugman** [comment]
Yes.

**Comment by sysads** [comment]
I know its about a year now but thanks for the reply. If so, how do I install it on shared hosting?

**Comment by sysads** [comment]
I unzipped the file into my hosting but its showing blank screen with following console error:

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by Brugman** [comment]
Unzip the release or repo locally, run `npm i` and `npm run build`, then upload the contents of the `dist` folder to your host.

**Comment by sysads** [comment]
G:\Downloads\chatgpt-app>npm run build

> patriks-chatgpt-implementation@0.0.0 build
> vite build

vite v4.5.3 building for production...
transforming (1) index.htmlBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✓ 119 modules transformed.
19:22:00 [vite-plugin-svelte] dom compile done.
package                         files    time      avg
patriks-chatgpt-implementation     34   1.58s   46.4ms
✓ built in 25.64s
"Configuration" is not exported by "node_modules/openai/index.mjs", imported by "src/App.svelte".
file: G:/Downloads/chatgpt-app/src/App.svelte:2:11
1: <script lang="ts">
2:   import { Configuration, OpenAIApi } from "openai";
              ^
3:   import type {
4:     ChatCompletionRequestMessage,
error during build:
RollupError: "Configuration" is not exported by "node_modules/openai/index.mjs", imported by "src/App.svelte".
    at error (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at FunctionScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at FunctionScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at TrackingScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at BlockScope.findVariable (file:///G:/Downloads/chatgpt-app/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)

**Comment by Brugman** [comment]
Works on my machine. `¯\_(ツ)_/¯`

Try reinstalling the latest stable Node.
